### ISSUE TITLE
Medical center/clinic

### ISSUE THREAD

**Issue by Strikor** [TheResimulators/Sim-U-Kraft-Resimulated#16]
I don't know about any of you but I always hated it when in chat I would just see that someone just died to something like a cave in or whatever in the old mod. What if having a hospital in your town gave you a chance that rather than dying immediately your sim would teleport to one of these places, stay there a night or two, and have a chance to recover from injuries and be just fine. This could also be expanded to adding something like a "Health" meter similar to happiness and rest. This could also be where pregnancies happen rather than children just appearing near the mother.

**Comment by aidie8** [comment]
Very good idea. that will be something we expand on when the mod is at a state where it is stable and has all features from the original mod.
