### ISSUE TITLE
[BUG] Builder crash

### ISSUE THREAD

**Issue by Sagez** [TheResimulators/Sim-U-Kraft-Resimulated#20]
After I hire builder at very first start to do then it gives purple particles then crash.

[crash-2019-03-15_10.26.03-server.txt](https://github.com/TheResimulators/Sim-U-Kraft-Resimulated/files/2971776/crash-2019-03-15_10.26.03-server.txt)

I expect builder would start to build after that.

plus I did compiled the source code today but, by comment off the "import com.sun.glass.ui.view;" in CommonProxy.java since it fail to comply the source. yet, I wasn't sure this is legal to be on this kind problem.

OS: Archlinux (kernel build: 4.20.7)
Java: 1.8.0_202-b26
Mod version: Compiled source code from 3/15/19 10:16 (it show 1.12.2-1.0-alpha92)
Minecraft: 1.12.2

**Comment by fabbe50** [comment]
Fixed
