### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Ijdtm7** [TheResimulators/Sim-U-Kraft-Resimulated#22]
Hey there, i think this is really good that you guys are remaking sim u craft, but there hasnt been any commits for a while. is this no longer being worked on?

**Comment by aidie8** [comment]
Hi @ljdtm7
we are still working on this. just life has been taking a lot of our time so we haven't had time to work on the mod. we are still hoping to get it done, at some point

**Comment by yanyiling** [comment]
I love this mod and I'm glad to hear that you're going to continue to make it. Come on, no matter when you can do it well. Please.

**Comment by Ijdtm7** [comment]
Glad it’s still being worked on! I understand about not having time for modding. It has happened to me

**Comment by fabbe50** [comment]
Hey everyone!

Just committed a little update. To make the mod more up to date, we're moving forward from 1.15 into 1.16 and will keep working on it for that version. Keep in mind that it'll take a while for the mod to be published, so your favorite mods will probably have updated by then. 

Thank you for your patience!
