### ISSUE TITLE
Building Options Won't Appear.

### ISSUE THREAD

**Issue by Flyer173** [TheResimulators/Sim-U-Kraft-Resimulated#8]
1.7.10
Latest build on the forum (1.0.4b)
All the other interfaces work, but when I click on Residual, Commercial, or any other tab that has building options, nothing comes up except for the words, Page back, and Done. Any solutions?
![silent oof](https://user-images.githubusercontent.com/25695949/41213373-f02ce390-6d12-11e8-96f9-19f4fb2b6cb4.PNG)

**Comment by general5001** [comment]
did you add the buildings but if you have any questions you can join our discord https://discord.gg/pVeZEuH

**Comment by Flyer173** [comment]
Add the buildings?
Dunno what you mean.
Also I am in the Discord.
I'm Flyer, joined the server recently.

**Comment by Astavie** [comment]
This is Sim-U-Kraft Resimulated (for 1.12), not Sim-U-Kraft Reloaded (for 1.7.10), which has been abandoned.
